name: PremiumPoints
version: '@version@'
authors: [padrewin]
website: 'https://github.com/padrewin/PremiumPoints'
description: An economy and currency system based on premium points
main: dev.padrewin.premiumpoints.PremiumPoints
api-version: '1.13'
load: STARTUP
softdepend: [Vault, Votifier, PlaceholderAPI, TokenManager, GamePoints, NexEngine]
loadbefore: [mcMMO]
folia-supported: true

commands:
  points:
    aliases: [p, pp, ppoints, premiumpoints, premiump]
    description: Root command for PremiumPoints
permissions:
  premiumpoints.*:
    description: Gives access to all PremiumPoints commands
    children:
      premiumpoints.give: true
      premiumpoints.giveall: true
      premiumpoints.take: true
      premiumpoints.look: true
      premiumpoints.pay: true
      premiumpoints.set: true
      premiumpoints.reset: true
      premiumpoints.me: true
      premiumpoints.lead: true
      premiumpoints.reload: true
      premiumpoints.broadcast: true
      premiumpoints.export: true
      premiumpoints.import: true
      premiumpoints.version: true
  premiumpoints.give:
    description: Gives access to the give command
    default: op
  premiumpoints.giveall:
    description: Gives access to the giveall command
    default: op
  premiumpoints.take:
    description: Gives access to the take command
    default: op
  premiumpoints.look:
    description: Gives access to the look command
    default: op
  premiumpoints.pay:
    description: Gives access to the pay command
    default: op
  premiumpoints.set:
    description: Gives access to the set command
    default: op
  premiumpoints.reset:
    description: Gives access to the reset command
    default: op
  premiumpoints.me:
    description: Gives access to the me command
    default: op
  premiumpoints.lead:
    description: Gives access to the lead command
    default: op
  premiumpoints.reload:
    description: Gives access to the reload command
    default: op
  premiumpoints.broadcast:
    description: Gives access to the broadcast command
    default: op
  premiumpoints.export:
    description: Gives access to the export command
    default: op
  premiumpoints.import:
    description: Gives access to the import command
    default: op
  premiumpoints.version:
    description: Gives access to the version command
    default: op
