name: Build and Publish Package

on:
  push:
    branches:
      - master
    paths:
      - 'src/main/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: false
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Create settings.xml with Personal Access Tokens using cat <<EOF
      - name: Create settings.xml
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/settings.xml
          <settings>
            <servers>
              <server>
                <id>colddev-repo</id>
                <username>padrewin</username>
                <password>${{ secrets.COLDDEV_REPO }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # Build the project using Maven (without publishing)
      - name: Build with Maven
        run: mvn package -s $GITHUB_WORKSPACE/settings.xml
        env:
          COLDDEV_PACKAGE: ${{ secrets.COLDDEV_REPO }}
          GITHUB_ACTOR: padrewin

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: "contains(github.event.commits[0].message, '[build]')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Re-create settings.xml from the GitHub secret for publish
      - name: Create settings.xml for publish
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/settings.xml
          <settings>
            <servers>
              <server>
                <id>colddev-repo</id>
                <username>padrewin</username>
                <password>${{ secrets.COLDDEV_REPO }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # Publish the package to GitHub Packages
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
